
//import java.awt.List;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Osmin Tovar
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JFrame();
        PanelPrincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        Iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        Principal.setPreferredSize(new java.awt.Dimension(1047, 540));

        PanelPrincipal.setBackground(new java.awt.Color(255, 250, 224));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1047, 540));
        PanelPrincipal.setLayout(null);

        jButton1.setText("Analisis de Ventas por Mes");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelPrincipal.add(jButton1);
        jButton1.setBounds(30, 40, 220, 43);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PanelPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 1220, 560);

        jButton2.setText("Filtrar Por Marca");
        PanelPrincipal.add(jButton2);
        jButton2.setBounds(260, 40, 120, 40);
        PanelPrincipal.add(jProgressBar1);
        jProgressBar1.setBounds(390, 40, 146, 40);

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal.getContentPane());
        Principal.getContentPane().setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 237, 201));
        jPanel1.setLayout(null);

        Iniciar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Iniciar.setText("Iniciar");
        Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarMouseClicked(evt);
            }
        });
        jPanel1.add(Iniciar);
        Iniciar.setBounds(500, 430, 140, 50);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 70)); // NOI18N
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 60, 400, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Osmin Tovar\\Documents\\NetBeansProjects\\segundoProyecto\\src\\main\\resources\\imagenes\\logo-ferco-nuevo-slogan.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 110, 690, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        SwingWorker<DefaultTableModel, Integer> worker = new SwingWorker<DefaultTableModel, Integer>() {
            @Override
            protected DefaultTableModel doInBackground() throws Exception {
                // Hilo para simular progreso
                Thread progressThread = new Thread(() -> {
                    try {
                        int progreso = 0;
                        while (!Thread.currentThread().isInterrupted()) {
                            publish(progreso);
                            progreso += 1;
                            if (progreso > 100) {
                                progreso = 0;  // Si quieres que la barra se reinicie
                            }
                            Thread.sleep(100); // cada 100 ms
                        }
                    } catch (InterruptedException e) {
                        // Thread interrumpido, salir
                    }
                });

                progressThread.start();

                // Aquí haces la conexión y la consulta real
                gestor = new SQLManagement();
                conn = gestor.conect();

                DefaultTableModel model = null;
                if (conn != null) {
                    model = gestor.VentasPorMesSinFiltroLlantas(conn);
                    conn.close();
                }

                // Termina el hilo del progreso
                progressThread.interrupt();
                progressThread.join();

                // Asegura que la barra quede llena al 100% al terminar
                publish(100);

                return model;
            }

            @Override
            protected void process(List<Integer> chunks) {
                int last = chunks.get(chunks.size() - 1);
                jProgressBar1.setValue(last);
            }

            @Override
            protected void done() {
                try {
                    DefaultTableModel model = get();
                    if (model != null) {
                        jTable1.setModel(model);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    jProgressBar1.setVisible(false);
                    jButton1.setEnabled(true);
                }
            }
        };

// Inicio
        jProgressBar1.setVisible(true);
        jProgressBar1.setValue(0);
        jButton1.setEnabled(false);
        worker.execute();

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);

        //PanelPrincipal.setLayout(BorderLayout);
        Principal.setExtendedState(JFrame.MAXIMIZED_BOTH);
        PanelPrincipal.setSize(Principal.getX(), Principal.getY());

        Principal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Principal.setLocationRelativeTo(null);

        Principal.add(PanelPrincipal);
        Principal.setVisible(true);

    }//GEN-LAST:event_IniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JFrame Principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
//Variables globales
    Connection conn = null;
    SQLManagement gestor = new SQLManagement();

    public interface ProgresoCallback {

        void onProgreso(int progreso);
    }
}
